[package]
name = "rust-src"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
async-std = "1.13.0"
godot = { version = "0.2.0", features = ["experimental-threads"] }
rand = "0.8.5"
